osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([
  "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz
  | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends
  -y icnsutils graphicsmagick xz-utils; fi
install:
- nvm install 7
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- npm install -g xvfb-maybe
- yarn
script:
- yarn run build
branches:
  only:
  - release
before_deploy:
- git config --local user.name "MateuLlull"
- git config --local user.email "mateullull88@gmail.com"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: AsnMhfcToVRYhpDWTp1UcynVZTwUFwpK4bz77gGWdPY3aA1YgFiHZJNO+e3nn2P600lCmq+neUCQxrXW1YZ9G9ZFGQADanAQM424aeYATxu1rXGdarOLDtiEwlGryprhSU3O/JZZg9Vt92I76I9EfC1PDIjZTUiAM3YBaWAqZuVngfPDt2aqm3xibcKphQczLXc63g+i21Yhjbysz8IDFPr40oidH+18n0AryKpY89yKQGRA9e7f6lg/Y9kj0ZOLgBPERrGEaKC5Onj6lvkAiBAoG5ayrAiPLLeyYc59aJRlYxRvcUTkIp0EVNtx7eqp3Nnsf2gRC/tNEF+bGLRSKSBfbWCCHOHk+i5ZlE0CVjnriIXjCGMKpoEZ75izhygjdmzPLGijVneJ2cSuHwJpcppkCGYH5o0/9kaRYQWCtw4F2y1HVS2RgXB37WtK+Np+iaoYdTF+DFJdkWtQxgaIdpQpwsl/JkoOyHI989JWyjNl8SKwkRs90SqWqff6hrP5h2p7Usf6dWm6dg9K0pfFhhGm91FG6HzzNXs5BEtiu1lf4AK5Y+fZGiMMuOugx8wQrElJAn0L/A70DYvMza7n7/ap32k1UWKmQbm0kSxEsD5T1kgIbgcKs36liWq0pLLAPy/jIDzr5Vn4J+NW9tuejdqdvcVA/l+sgKAcxAQ4ESk=
